PicketFence/urls.py
from django.conf.urls import url, include
from django.contrib import admin
#form django.urls import path

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^announcements/', include('announcements.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^forms/', include('forms_app.urls')),
    url(r'^markbook/', include('marks.urls')),
    url(r'^accounts/', include('accounts.urls'))
]

marks/urls.py
from django.conf.urls import url
from . import views
#form django.urls import path

urlpatterns = [
    url(r'^$', views.index),
    url(r'^(?P<markbookId>\d+)/$', views.index),
    url(r'^(?P<markbookId>\d+)/results/$', views.results),
    url(r'^results/edit/$', views.editingResults),
    url(r'^(?P<markbookId>\d+)/(?P<lessonId>\d+)/$', views.editLesson),
]

marks/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

from users.models import schForm, Staff, Student

# Create your models here.
class Period(models.Model):
    title = models.CharField(max_length = 150)
    begin = models.DateField()
    end = models.DateField()

    class Meta:
        verbose_name = (u'Период')
        verbose_name_plural = (u'Периоды')

    def __unicode__(self):
        return u"%s" % self.title

    def __str__(self):
        return self.__unicode__()

class Subject(models.Model):
    title = models.CharField(max_length = 150)

    class Meta:
        verbose_name = (u'Предмет')
        verbose_name_plural = (u'Предметы')

    def __unicode__(self):
        return u"%s" % self.title

    def __str__(self):
        return self.__unicode__()

class Markbook(models.Model):
    form = models.ForeignKey(schForm, on_delete = models.DO_NOTHING)
    subject = models.ForeignKey(Subject, on_delete = models.DO_NOTHING)
    period = models.ForeignKey(Period, on_delete = models.DO_NOTHING)
    teacher = models.ForeignKey(Staff, on_delete = models.DO_NOTHING)

    class Meta:
        verbose_name = (u'Журнал')
        verbose_name_plural = (u'Журналы')

    def __unicode__(self):
        return u"%s" % (str(self.form.year) + "-" + str(self.form.number) + " " + self.subject.title + " " + self.period.title)

    def __str__(self):
        return self.__unicode__()

class Lesson(models.Model):
    markbook = models.ForeignKey(Markbook, on_delete = models.DO_NOTHING)
    date = models.DateField()
    topic = models.CharField(max_length = 150, blank = True)
    hometask = models.CharField(max_length = 150, blank = True)
    num = models.IntegerField(blank = True, null = True)
    class Meta:
        verbose_name = (u'Урок')
        verbose_name_plural = (u'Уроки')

    def __unicode__(self):
        return u"%s" % self.markbook + " --- " + str(self.date) + "(" + str(self.num) + ")"

    def __str__(self):
        return self.__unicode__()

# class Hometask(models.Model):
#     lesson = models.ForeignKey(Lesson, on_delete = models.DO_NOTHING)
#     title = models.CharField(max_length = 150)
#     class Meta:
#         verbose_name = (u'Домашнее задание')
#         verbose_name_plural = (u'Домашние задания')
#     def __unicode__(self):
#         return u"%s" % self.lesson + " --- " + self.title
#     def __str__(self):
#         return self.__unicode__()

# class HometaskMark(models.Model):
#     hometask = models.ForeignKey(Hometask, on_delete = models.DO_NOTHING)
#     student = models.ForeignKey(Student, on_delete = models.DO_NOTHING)
#     mark = models.IntegerField(blank = True, null = True)
#     class Meta:
#         verbose_name = (u'Оценка за д/з')
#         verbose_name_plural = (u'Оценки за д/з')
#     def __unicode__(self):
#         return u"%s" % self.hometask + " --- " + unicode(self.student) + " --- " + str(self.mark)
#     def __str__(self):
#         return self.__unicode__()

class WorkType(models.Model):
    title = models.CharField(max_length = 150)
    titleSh = models.CharField(max_length = 2)
    weight = models.FloatField()
    class Meta:
        verbose_name = (u'Тип работ')
        verbose_name_plural = (u'Типы работ')
    def __unicode__(self):
        return u"%s" % self.title + " (" + str(self.weight) + ")"
    def __str__(self):
        return self.__unicode__()

class Work(models.Model):
    lesson = models.ForeignKey(Lesson, on_delete = models.DO_NOTHING)
    type = models.ForeignKey(WorkType, on_delete = models.DO_NOTHING)
    class Meta:
        verbose_name = (u'Работа')
        verbose_name_plural = (u'Работы')
    def __unicode__(self):
        return u"%s" % self.lesson + " --- " + unicode(self.type)
    def __str__(self):
        return self.__unicode__()

class WorkMark(models.Model):
    work = models.ForeignKey(Work, on_delete = models.DO_NOTHING)
    student = models.ForeignKey(Student, on_delete = models.DO_NOTHING)
    mark = models.IntegerField(blank = True, null = True)
    class Meta:
        verbose_name = (u'Оценка за работу')
        verbose_name_plural = (u'Оценки за работы')
    def __unicode__(self):
        return u"%s" % self.work + " --- " + unicode(self.student) + " --- " + str(self.mark)
    def __str__(self):
        return self.__unicode__()

class Result(models.Model):
    markbook = models.ForeignKey(Markbook, on_delete = models.DO_NOTHING)
    student = models.ForeignKey(Student, on_delete = models.DO_NOTHING)
    mark = models.CharField(max_length = 3)
    class Meta:
        verbose_name = (u'Итоговая оценка')
        verbose_name_plural = (u'Итоговые оценки')
    def __unicode__(self):
        return u"%s" % self.markbook + " --- " + unicode(self.student) + " --- " + unicode(self.mark)
    def __str__(self):
        return self.__unicode__()

class Absence(models.Model):
    student = models.ForeignKey(Student, on_delete = models.DO_NOTHING)
    lesson = models.ForeignKey(Lesson, on_delete = models.DO_NOTHING)
    value = models.CharField(max_length = 2, blank = True, null = True)

marks/forms.py
# -*- coding: utf-8 -*-
from django import forms

from .models import Markbook, WorkType

class MarkbookForm(forms.Form):
    markbook = forms.ModelChoiceField(queryset = Markbook.objects.all(), widget = forms.Select(attrs={'onchange': "showMarkbook();"}))

class NewMarkbookForm(forms.Form):
    date = forms.DateField()
    title = forms.CharField(label = 'Тема урока', widget = forms.TextInput(attrs={'size': 60}))

class LessonForm(forms.Form):
    # date = forms.DateField(label = 'Дата урока', widget = forms.SelectDateWidget())
    topic = forms.CharField(label = 'Тема урока', widget = forms.TextInput(attrs={'size': 60}), required = False)
    hometask = forms.CharField(label = 'Домашнее задание', widget = forms.TextInput(attrs={'size': 60}), required = False)
    type = forms.ModelChoiceField(queryset = WorkType.objects.all(), empty_label = None, to_field_name = 'id', widget = forms.Select())

marks/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

from .forms import MarkbookForm, LessonForm

from .models import Markbook, Lesson, WorkMark, Work, Result, WorkType, Absence
from users.models import Student

from operator import attrgetter

from collections import OrderedDict

from django.http import HttpResponseRedirect

from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required
def index(request, markbookId = ''):
    if markbookId == '0':
        try:
            del request.session['openedMarkbook']
            return HttpResponseRedirect("/markbook/")
        except:
            pass
    if markbookId == '':
        if 'openedMarkbook' in request.session:
            return HttpResponseRedirect("/markbook/" + str(request.session['openedMarkbook']) + "/")
        else:
            MarkbookChoice = MarkbookForm()
            return render(request, "marks/index.html", {"title": "Классный журнал", "MarkbookChoice": MarkbookChoice, "error": True})
    else:
        request.session['openedMarkbook'] = markbookId
        markbook = Markbook.objects.get(id = int(markbookId))
        MarkbookChoice = MarkbookForm({'markbook': markbook})
    # if ((request.method == 'POST') or ('openedMarkbook' in request.session)) and (request.POST.get('markbook') <> "") :
    #     if not 'markbook' in request.POST:
    #         markbook = Markbook.objects.get(id = request.session['openedMarkbook'])
    #         MarkbookChoice = MarkbookForm({'markbook': markbook})
    #     else:
    #         MarkbookChoice = MarkbookForm(request.POST)
    #         request.session['openedMarkbook'] = request.POST.get('markbook')
    #         markbook = Markbook.objects.get(id = request.POST.get('markbook'))
        students = Student.objects.filter(schForm = markbook.form)
        students = sorted(students, key = attrgetter('user.last_name', 'user.first_name'))
        lessons = Lesson.objects.filter(markbook = markbook)
        lessons = sorted(lessons, key = attrgetter('date', 'num'))
        n = 1 #Для нумерации учеников в списке
        result = {} #Список словарей (содержит все данные журнала)
        dates = [] #Список дат всех уроков (сколько дат -- столько уроков)
        types = []
        q = 0 #Количество уроков
        months = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] #Список, содержащий информацию и количестве уроков в каждом месяце
        m = 1 #Месяц на проверку (изначально -- январь)
        c = 0
        works_num_com = 0
        for lesson in lessons:
            works = Work.objects.filter(lesson = lesson)
            works_num = works.count()
            for work in works:
                type = [work.type.titleSh, str(work.type.weight), 0]
                types.append(type)
            if works_num == 0:
                works_num = 1
                types.append(["", "", 0])
            types[works_num_com][2] = 1
            works_num_com += works_num
            date_cor = (lesson.date.day, works_num, lesson.id)
            dates.append(date_cor)
            q = q + 1
            # hometasks = Hometask.objects.filter(lesson = lesson)
            works = Work.objects.filter(lesson = lesson)
            b = True
            for work in works:
                c += 1
                b = False
            if b:
                c += 1
            while int(lesson.date.month) > m:
                m = m + 1
            months[m-1] = months[m-1] + works_num
        result = OrderedDict()
        #results = []
        for student in students:
            name = str(n) + ". " + student.user.last_name + " " + student.user.first_name
            n = n + 1
            row = []
            #rowForResults = [student.id, name]
            sum = 0
            w = 0
            for lesson in lessons:
                works = Work.objects.filter(lesson = lesson)
                a = True
                for work in works:
                    a = False
                    WorkMarks = WorkMark.objects.filter(work = work, student = student)
                    mks = ""
                    b = True
                    for wm in WorkMarks:
                        if wm.mark is not None:
                            mks = mks + unicode(wm.mark) + " "
                            # row.append(unicode(hm.mark))
                            sum = sum + wm.mark * wm.work.type.weight
                            w = w + wm.work.type.weight
                            b = False
                    row.append(mks)

                if a:
                    row.append("")
            if w > 0:
                average = str(format(sum / w, '.2f'))
            else:
                average = ""
            row.append(average)
            #rowForResults.append(average)
            resultMarks = Result.objects.filter(markbook = markbook, student = student)
            resultMarkStr = ""
            row.append("")
            for resultMark in resultMarks:
                resultMarkStr += unicode(resultMark.mark)
            row.append(unicode(resultMarkStr))
            #rowForResults.append(unicode(resultMarkStr))
            result[name] = row
            #results.append(rowForResults)

        rated = OrderedDict(sorted(result.iteritems(), key = lambda st: st[1][c], reverse = True))
        i = 1
        last = "-"
        ratings = []
        for name in rated:
            if result[name][c] != "":
                if last == result[name][c]:
                    i += 1
                else:
                    ratings.append(i)
                    i = 1
                last = result[name][c]
            else:
                break
        ratings.append(i)
        i = 1
        a = 1
        n = 0
        b = 0
        ratings_ = ratings[:]
        for name in rated:
            if result[name][c] <> "":
                if b == 0:
                    b = ratings[i]
                if a == b:
                    strRating = str(a)
                else:
                    strRating = str(a) + "-" + str(b)
                if ratings_[i] > 0:
                    result[name][c+1] = strRating
                    ratings_[i] -= 1
                    n += 1
                else:
                    i += 1
                    a = b + 1
                    b = b + ratings[i]
                    ratings_[i] -= 1
                    #a = n
                    if a == b:
                        strRating = str(a)
                    else:
                        strRating = str(a) + "-" + str(b)
                    result[name][c+1] = strRating
                    n += 1
            else:
                result[name][c+1] = ""
        #rated = sorted(announcements, key = lambda announcement: announcement.date_pub, reverse = True)
        names = list(result.keys())
        names.sort()


        return render(request, "marks/index.html", {"title": "Классный журнал",
                                                    "MarkbookChoice": MarkbookChoice,
                                                    "students": students,
                                                    "dates": dates, "q": q,
                                                    "months": months, "result": result,
                                                    "types": types, "d": markbookId})
    # else:
    #     MarkbookChoice = MarkbookForm()
    #     try:
    #         del request.session['openedMarkbook']
    #     except:
    #         pass
    #     return render(request, "marks/index.html", {"title": "Классный журнал", "MarkbookChoice": MarkbookChoice, "error": True})

@login_required
def results(request, markbookId):
    markbook = Markbook.objects.get(id = markbookId)
    students = Student.objects.filter(schForm = markbook.form)
    students = sorted(students, key = attrgetter('user.last_name', 'user.first_name'))
    resultsT = []
    n = 1
    for student in students:
        row = [str(student.id), str(n) + ". " + student.user.last_name + " " + student.user.first_name]
        # results = Result.objects.get(markbook__id = markbook.id, student__id = student.id)
        try:
            results = Result.objects.get(markbook__id = markbook.id, student__id = student.id)
            resultForRow = str(results.mark)
        except:
            resultForRow = ""
        # resultForRow = ""
        # for result in results:
        #     resultForRow += str(result.mark)
        row.append(resultForRow)
        resultsT.append(row)
        n += 1
    return render(request, "marks/results.html", {"title": "Итоговый оценки",
                                                    "results": resultsT,
                                                    "markbook": markbook.id})
@login_required
def editingResults(request):
    if request.method == 'POST':
        markbook = Markbook.objects.get(id = request.POST.get('markbook'))
        students = Student.objects.filter(schForm = markbook.form)
        for student in students:
            result = Result.objects.update_or_create(markbook__id = markbook.id, student__id = student.id, defaults = {'markbook': markbook, 'student': student, 'mark': request.POST.get(str(student.id))})
    return HttpResponseRedirect("/markbook/")

@login_required
def editLesson(request, markbookId, lessonId):
    lesson = Lesson.objects.get(id = int(lessonId))
    markbook = Markbook.objects.get(id = markbookId)
    students = Student.objects.filter(schForm = markbook.form)
    students = sorted(students, key = attrgetter('user.last_name', 'user.first_name'))
    cols = Work.objects.filter(lesson__id = lessonId)
    if request.method == 'POST':
        lesson.topic = request.POST['topic']
        lesson.hometask = request.POST['hometask']
        # lesson.num = request.POST['num']
        lesson.save()
        for student in students:
            absence = Absence.objects.filter(student = student, lesson = lesson).delete()
            if request.POST[str(student.id)] <> '':

marks/templates/marks/edit.html
{% extends "marks/wrapper.html" %}

{% load staticfiles %}



{% block main %}
<style media="screen">
  td{
    border: 0;
  }
</style>
<script type="text/javascript">
function addWork(){
  var rows = $('#main tr');
  var cell = document.createElement('td');
  var typeI = document.querySelector('#id_type').options.selectedIndex;
  var typeV = document.querySelector('#id_type').options[typeI].value;
  var typeT = document.querySelector('#id_type').options[typeI].text;
  var text = document.createTextNode(typeT);
  var dIcon = document.createElement('img');
  dIcon.src = "{% static 'announcements/images/delete.png' %}";
  dIcon.style.height = '15px';
  dIcon.classList.add('deleteColB');
  $(dIcon).click(function(){
    deleteWork($(this));
  });
  cell.appendChild(text);
  cell.appendChild(document.createElement('br'));
  cell.appendChild(dIcon);
  rows[0].appendChild(cell);
  for (i = 1; i < rows.length; i++){
    var cell = document.createElement('td');
    var field = document.createElement('input');
    field.type = 'text';
    field.size = 3;
    cell.appendChild(field);
    rows[i].appendChild(cell);
    field.name = "new_" + document.querySelector('#num').value + "_" + rows[i].querySelectorAll('td')[1].firstChild.name;
  }
  document.querySelector('#count').value += typeV + "__";
  document.querySelector('#num').value++;
}
function deleteWork(i){
  if(confirm('Удалить колонку?')){
    var n = $(i).parent().parent().children().index($(i).parent());
    // var table = $('.main');
    var rows = $('#main tr');
    rows.each(function(){
      $(this).children('td:eq(' + n + ')').detach();
    });
  }
}
</script>
<form class="" action="" method="post">
  {% csrf_token %}
  <table style = "width: auto; border: 0">
    <!-- <tr>
      <td>Дата урока</td>
      <td><input type="date" name="" value=""></td>
    </tr> -->
    <tr>
      <td><b>{{ editLessonForm.topic.label }}</b></td>
      <td>{{ editLessonForm.topic }}</td>
    </tr>
    <tr>
      <td><b>{{ editLessonForm.hometask.label }}</b></td>
      <td>{{ editLessonForm.hometask }}</td>
    </tr>
    <!-- <tr>
      <td><b>{{ editLessonForm.num.label }}</b></td>
      <td>{{ editLessonForm.num }}</td>
    </tr> -->
  </table>
  Для добавления колонки используйте этот выпадающий список: {{ editLessonForm.type }} <input type="button" name="" value="Добавить" onclick="addWork();">
  <table style = "width: auto; border: 0" id = 'main'>
    <tr id = 'f'>
      <td></td>
      <td>Посещаемость</td>
      {% for work in works %}
        <td name = 'lksd'> {{ work.type }}<br><img class = 'deleteColB' src = "{% static 'announcements/images/delete.png' %}" style="height: 15px"></img></td>
      {% endfor %}
    </tr>
    {% for row in grand %}
      <tr>
        <td>{{ row.0 }}</td>
        <td><select class="" name="{{ row.1.0 }}">
          {% if row.1.1 == 'ОТ' %}
          <option value=""></option>
          <option value="ОТ" selected>ОТ</option>
          {% else %}
          <option value="" selected></option>
          <option value="ОТ">ОТ</option>
          {% endif %}

        </select></td>
        {% for mark in row.2 %}
          <td><input type="text" name="{{ mark.0 }}" value="{{ mark.1 }}" size = '3'></td>
        {% endfor %}
      </tr>
    {% endfor %}
  </table>
  <input type="hidden" id = 'count' name="count" value="">
  <input type="hidden" id = 'num' name="num" value="0">
  <input type="submit" name="submit" value="Сохранить">
</form>
<script type="text/javascript">
  $('.deleteColB').click(function(){
    deleteWork($(this));
  });
</script>
{% endblock main %}

marks/templates/marks/index.html
{% extends "marks/wrapper.html" %}

{% load staticfiles %}



{% block main %}
<script type="text/javascript">
  function showMarkbook(){
    url =  'http://' + document.location.host + '/markbook/' + document.getElementById("id_markbook").options.selectedIndex;
    document.location.href = url;
  }
</script>
<style>
fieldset {
  overflow: hidden;
  width: 20%;
  min-width: 100px;
  display: table-cell;
  margin: 0;
  margin-bottom: 10px;
}
</style>
<form class="" action="/markbook/" method="post">
  {% csrf_token %}
  <fieldset>
    <legend>Выбор журнала</legend>
    {{ MarkbookChoice.markbook }}
  </fieldset>
  <!--<input type="submit" value="Открыть"></input>-->
  <!--<input type="button" value="Создать новый журнал" onclick="javascript:window.location='http://127.0.0.1:8000/markbook/'">-->
</form>
{% if error %}
Выберите журнал для отображения.
{% else %}
<!-- <form class="" action="index.html" method="post">
  <fieldset>
    <legend>Добавление урока</legend>
    <input type="date" name="" value="">
    <input type="button" name="addLessonButton" value="Добавить урок" onclick="addLesson()">
  </fieldset>
</form> -->
<table style = "width: auto" id = 'main'>
  <tr height = "12px">
    <th rowspan="3">Ученик</th>
    {% if months.0 != 0 %}
      <th colspan="{{ months.0 }}">Январь</th>
    {% endif %}
    {% if months.1 != 0 %}
      <th colspan="{{ months.1 }}">Февраль</th>
    {% endif %}
    {% if months.2 != 0 %}
      <th colspan="{{ months.2 }}">Март</th>
    {% endif %}
    {% if months.3 != 0 %}
      <th colspan="{{ months.3 }}">Апрель</th>
    {% endif %}
    {% if months.4 != 0 %}
      <th colspan="{{ months.4 }}">Май</th>
    {% endif %}
    {% if months.5 != 0 %}
      <th colspan="{{ months.5 }}">Июнь</th>
    {% endif %}
    {% if months.6 != 0 %}
      <th colspan="{{ months.6 }}">Июль</th>
    {% endif %}
    {% if months.7 != 0 %}
      <th colspan="{{ months.7 }}">Август</th>
    {% endif %}
    {% if months.8 != 0 %}
      <th colspan="{{ months.8 }}">Сентябрь</th>
    {% endif %}
    {% if months.9 != 0 %}
      <th colspan="{{ months.9 }}">Октябрь</th>
    {% endif %}
    {% if months.10 != 0 %}
      <th colspan="{{ months.10 }}">Ноябрь</th>
    {% endif %}
    {% if months.11 != 0 %}
      <th colspan="{{ months.11 }}">Декабрь</th>
    {% endif %}
    <th rowspan="3" width="70px">Средний балл</th>
    <th rowspan="3" width="70px">Рейтинг</th>
    <th rowspan="3" width="70px">Итоговая оценка<br><a href="results/"><img src = "{% static 'announcements/images/edit.png' %}" style="height: 15px"></img></a></th>
  </tr>
  <tr height='9px'>
    {% for date in dates %}
      <td align = 'center' valign = 'center' style="background-color: #b3b3b3; min-width: 20px;  border-bottom: 0" colspan="{{ date.1}}"><b>{{ date.0 }}</b><br>
        <a href="{{ date.2 }}/"><img src = "{% static 'announcements/images/edit.png' %}" style="height: 10px"></img></a>
      </td>
    {% endfor %}
  </tr>
  <tr>
    {% for type in types %}
      <td align = 'center' valign = 'center' style="background-color: #b3b3b3; min-width: 20px; font-size: 8pt; border-right: 0;  border-left: {{ type.2 }};  border-top: 0">{{ type.0 }}<br>{{ type.1 }}</td>
    {% endfor %}
  </tr>
  {% for name, marks in result.items %}
  <tr class = "row">
    <td valign = 'center'>{{ name }}</td>
    {% for day in marks %}
      <td align = 'center' valign = 'center' style="min-width: 20px">{{ day }}</td>
    {% endfor %}
  </tr>
  {% endfor %}
</table>
{% endif %}
{% endblock main %}

marks/templates/marks/results.html
{% extends "marks/wrapper.html" %}

{% load staticfiles %}



{% block main %}
<form class="" action="/markbook/results/edit/" method="post">
  {% csrf_token %}
  <table style = "width: auto; border: 0">
    <tr>
      <td style = "border: 0"><b>Ученик</b></td>
      <td style = "border: 0"><b>Оценка</b></td>
    </tr>
    {% for result in results %}
    <tr>
      <td style = "border: 0">{{ result.1 }}</td>
      <td style = "border: 0"><input type="text" name="{{ result.0 }}" value="{{ result.2}}" size = '1'></td>
    </tr>
    {% endfor %}
  </table>
  <input type="hidden" name="markbook" value="{{ markbook }}">
  <input type="submit" name="submit" value="Сохранить и вернуться">
</form>
{% endblock main %}

marks/templates/marks/wrapper.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{{ title }}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'users/style.css' %}" type="text/css">
    <script type="text/javascript" src=" https://code.jquery.com/jquery-1.11.2.js "></script>
  </head>
  <body>
    <div class="header" style="">
      <div class="left" style="">
        <ul class = "mainmenuul">
          {% load menubuilder %}

          {% menu mainmenu %}

          {% for item in menuitems %}
          <li {% if item.current %}style="font-weight: bold"{% endif %} class = "mainmenuli">
            <a class = "mainmenuitem" href="{{ item.url }}" title="{{ item.title|escape }}">{{ item.title }}</a>
          </li>
          {% endfor %}
          <li style="font-weight: bold; float: right;" class = "mainmenuli"> <a class = "mainmenuitem" href="/accounts/logout/" title="{{ item.title|escape }}">Выход</a></li>
          <li style="float: right;" class = "mainmenuli"><a class = "mainmenuitem" href="" title=""><i>{{user.first_name }} {{user.last_name }}</i></a></li>
        </ul>
      </div>
    </div>
    <div class="main">
      <h1>{{ title }}</h1>
      {% block main %}

      {% endblock main %}
    </div>
  </body>
</html>